output_dir: null
notes: no_resample_l2div
dataset:
  name: 'coco_imbatt_balcls'
  data_path: './_coco/ALT/coco_cbl'
  rand_aug: True
  rgb_mean: [0.473, 0.429, 0.370]
  rgb_std: [0.277, 0.268, 0.274]


sampler: default    
num_sampler: 1
seed:
  dataset: 123

networks:
  type: ResNet_MH
  params: 
    m_type: 'resnet18'
    num_classes: 29
    num_head: 4

algorithm_opt:
  entropy_weight: 1.0
  warmup_epoch: 0
  weight_lr: [1000,50]


training_opt:
  type: MH6
  num_epochs: 200
  batch_size: 256
  data_workers: 4
  loss: 'MH3Loss'
  loss_params: 
    diversity_weight: -1.0 
    diversity_temperature: 1.0
    diversity_loss_type: 'l2'
  optimizer: 'SGD'
  optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
  scheduler: 'cosine'
  scheduler_params: {endlr: 0.0, gamma: 0.1, step_size: 35, milestones: [120, 160]}

testing_opt:
  type: baseline  # baseline / TDE

logger_opt:
  print_iter: 100

